#!/bin/sh /etc/rc.common

. /lib/functions/bos-defaults.sh
. /lib/functions/esp32-wifi.sh

USE_PROCD=1

START=13
STOP=99

APP=/usr/bin/esp32-fw-log

flash_firmware_local() {
    if is_factory_default; then
        # It's in factory default state, configure AP mode
        logger -t esp32-wifi "Loading FG firmware"
        flash_fg_firmware
        modprobe esp32-sdio-fg
    else
        # It's NOT in factory default state, configure STA mode
        logger -t esp32-wifi "Loading NG firmware"
        flash_ng_firmware
        modprobe esp32-sdio
    fi
}

boot() {
    flash_firmware_local
    start "$@"
}

start_service() {
    procd_open_instance
    procd_set_param command "$APP" "$ESP32_UART_PATH" "115200"
    procd_set_param respawn 3600 5 1
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/esp32-log.pid
    procd_close_instance
}

reload_service()
{
    stop
    flash_firmware_local
    start "$@"
}
